name: firebase
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: any
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  logging: "^0.11.3"
  throttle_debounce: "^0.1.2"
  fnx_ui:
    git:
      url: https://github.com/fnx-io/fnx_ui
      ref: master
  firebase3: ^0.2.0
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    - 'package:angular2/common.dart#CORE_DIRECTIVES'
    - 'package:angular2/router.dart#ROUTER_DIRECTIVES'
    - 'package:fnx_ui/fnx_ui.dart#FNX_UI_COMPONENTS'
    entry_points: web/main.dart
    resolved_identifiers:
      Database: 'package:firebase3/firebase.dart'
      Auth: 'package:firebase3/firebase.dart'
- dart_to_js_script_rewriter